server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 200 # ????? ???
    open-in-view: false # ???? ??? ??? ??


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

kakao:
  client:
    id: 0bb8b2467b95230fe1f9b959758428b1
    secret: BihBWJYa4dMxrrVNeXaLKrcnsjWtmrN7

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 500

logging:
  level:
    org.hibernate.type: trace  # ? ??? ??? ??
    com.app: debug

token:
  secret: tempString
  access-token-expiration-time: 900000
  refresh-token-expiration-time: 1209600000